In [1]:
import numpy as np

In [3]:
a = [1,2,3]
print(a)
print(type(a))
b = np.array(a)
print(type(b))

[1, 2, 3]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
c = [[1,2,3],[4,5,6],[7,8,9]]
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
x = np.ones((3,3))
y = np.zeros(5)
print(x)
print(y)
type(x[0])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]


numpy.ndarray

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.linspace(0, 20, 20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [21]:
np.random.rand(5,5)

array([[0.26665402, 0.2557016 , 0.12146229, 0.9782168 , 0.87185789],
       [0.91148976, 0.67676202, 0.48403543, 0.16447021, 0.53112227],
       [0.30996112, 0.24573107, 0.40127344, 0.19911401, 0.52668009],
       [0.61898747, 0.15242868, 0.68829193, 0.51713273, 0.96721378],
       [0.83072339, 0.49807545, 0.29868463, 0.48020268, 0.57142213]])

In [22]:
np.random.randn(5,5)

array([[-0.52994355,  1.87886488,  0.31633163, -0.34604706,  0.09878415],
       [ 0.7068423 , -0.56157063,  1.92493622, -1.23411169,  0.22583761],
       [ 2.52556841,  0.18972739, -2.02343556,  0.71803966,  0.31875138],
       [ 0.81061181, -1.45831389,  0.44844289, -1.6045819 , -0.01689687],
       [ 2.00647075, -0.64674698, -0.33384634,  0.95080417,  1.04977011]])

In [23]:
np.random.randint(1,100,5)

array([82, 49, 98, 48, 28])

In [13]:
x = np.random.randint(0,10,5)
print(x.shape)

y = np.random.rand(5,10)
print(y.shape)


(5,)
(5, 10)


In [25]:
y = np.random.randn(10,10)
y.shape

(10, 10)

In [31]:
z = np.linspace(0,20,10)
z.shape
z.reshape(2,5)

array([[ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889],
       [11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ]])

In [19]:
arr = np.random.rand(10,5)
print(arr)
print(arr.shape)

arr.reshape(25,2)

[[0.81314705 0.36604411 0.21152364 0.30986251 0.30543825]
 [0.45480002 0.93975351 0.74452441 0.17259224 0.86760439]
 [0.96439961 0.90063924 0.71668898 0.49324139 0.54644833]
 [0.08869401 0.90497768 0.53333217 0.99300006 0.56384192]
 [0.26838689 0.62363633 0.78543702 0.09317569 0.52862445]
 [0.76275375 0.68557572 0.14229147 0.88351185 0.53157665]
 [0.4050873  0.97624367 0.60461646 0.34137177 0.69085897]
 [0.18204386 0.53323947 0.40073192 0.464834   0.66743717]
 [0.98018374 0.13137713 0.16907249 0.69225811 0.84039696]
 [0.5075471  0.46121196 0.32955265 0.45541814 0.02290283]]
(10, 5)


array([[0.81314705, 0.36604411],
       [0.21152364, 0.30986251],
       [0.30543825, 0.45480002],
       [0.93975351, 0.74452441],
       [0.17259224, 0.86760439],
       [0.96439961, 0.90063924],
       [0.71668898, 0.49324139],
       [0.54644833, 0.08869401],
       [0.90497768, 0.53333217],
       [0.99300006, 0.56384192],
       [0.26838689, 0.62363633],
       [0.78543702, 0.09317569],
       [0.52862445, 0.76275375],
       [0.68557572, 0.14229147],
       [0.88351185, 0.53157665],
       [0.4050873 , 0.97624367],
       [0.60461646, 0.34137177],
       [0.69085897, 0.18204386],
       [0.53323947, 0.40073192],
       [0.464834  , 0.66743717],
       [0.98018374, 0.13137713],
       [0.16907249, 0.69225811],
       [0.84039696, 0.5075471 ],
       [0.46121196, 0.32955265],
       [0.45541814, 0.02290283]])

In [20]:
arr.reshape(-1)
print(arr.reshape(-1).shape)

(50,)


In [22]:
x = np.random.randint(1,100,10)
print(x)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())

[90 77  2 32 14 16 84 28  7 62]
90
0
2
2


In [23]:
x.dtype

dtype('int64')

In [25]:
arr.dtype

dtype('float64')

In [7]:
x = np.arange(0,11)
print(x)
print(x[2])
print(x[:7])
print(x[1:10:3])

[ 0  1  2  3  4  5  6  7  8  9 10]
2
[0 1 2 3 4 5 6]
[1 4 7]


In [9]:
x[0:2] = 100
x

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [15]:
x_slice = x[0:2]
x_slice[:] = 20
print(x_slice)
print(x)


[20 20]
[20 20  2  3  4  5  6  7  8  9 10]


In [22]:
x_slice = x[0:2].copy()
x_slice[:] = 40
print(x)
print(x_slice)
print(x)

[20 20  2  3  4  5  6  7  8  9 10]
[40 40]
[20 20  2  3  4  5  6  7  8  9 10]


In [23]:
x[[0,4,2,7,1]]

array([20,  4,  2,  7, 20])

In [25]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr_2d)
arr_2d[[1,2]]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[20, 25, 30],
       [35, 40, 45]])

In [26]:
arr = np.arange(1,11)
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])