In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
print(1/arr)
print(arr*arr)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[ 1  4  9 16 25 36 49 64 81]


In [7]:
arr_2d = arr.reshape(3,3)
arr_x = np.random.randint(1,10,3)
print(arr_2d**2)
print(arr_2d*arr_x)
print(arr_2d/arr_x)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 9 10 18]
 [36 25 36]
 [63 40 54]]
[[0.11111111 0.4        0.5       ]
 [0.44444444 1.         1.        ]
 [0.77777778 1.6        1.5       ]]


In [8]:
np.sqrt(arr**2)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [12]:
np.log(np.exp(arr))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [15]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [16]:
print(arr)
np.insert(arr,6,100)

[1 2 3 4 5 6 7 8 9]


array([  1,   2,   3,   4,   5,   6, 100,   7,   8,   9])

In [18]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [19]:
np.append(arr,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

In [63]:
a = arr.reshape(3,3)
b = np.array([[10,11,12]])
print(a.shape)
print(b.shape)

(3, 3)
(1, 3)


In [51]:
print(np.concatenate((a,b), axis = 0))
print(np.concatenate((a,b.T),axis=1))
print(np.concatenate((a,b),axis=None))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [54]:
print(arr)
print(np.where(arr>5,1,arr))
print(np.where(arr>5,1,0))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 1 1 1 1]
[0 0 0 0 0 1 1 1 1]


In [59]:
print(arr_2d)
print(np.where(arr_2d <= 5,0, arr_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 6]
 [7 8 9]]
